#There are six ways to create an array.
#arry, linspace, logspace,arange,zeros,ones.

In [6]:
from numpy import*

arr = array([1,2,3,4,5],float)

print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [8]:
# using linspace(start, stop, step) to create an array.

arr = linspace(0,15,20) # the values 0 to 15 will be divided into 15 parts.

print(arr)


[ 0.          0.78947368  1.57894737  2.36842105  3.15789474  3.94736842
  4.73684211  5.52631579  6.31578947  7.10526316  7.89473684  8.68421053
  9.47368421 10.26315789 11.05263158 11.84210526 12.63157895 13.42105263
 14.21052632 15.        ]


In [9]:
#Using arange to create an array.

arr = arange(1,15,2)

print(arr)

[ 1  3  5  7  9 11 13]


In [12]:
#Using log space to create an array.
arr = logspace(1,40,5)

print('%.2f' %arr[4])

10000000000000000303786028427003666890752.00


In [14]:
#Using zeros to create an array.

arr = ones(5, int)

print(arr)

[1 1 1 1 1]
