In [1]:
from numpy import*

In [2]:
arr1 = array([
               [1,2,3],
               [4,5,6]
])

In [3]:
print(arr1.ndim)

2


In [4]:
print(arr1.shape)

(2, 3)


In [5]:
print(arr1.size)

6


In [6]:
#Multi dimensional to single dimensional.
arr2 = arr1.flatten()

In [17]:
print(arr2)

[1 2 3 4 5 6]


In [19]:
#single dimensional to multiple dimensional.
arr3 = arr2.reshape(2,3)

In [20]:
print(arr3)

[[1 2 3]
 [4 5 6]]


In [25]:
arr1 = ([
    [1,2,3,6],
    [4,5,67]
])

In [53]:
m1 = matrix('1 2 3; 6 4 5; 1 6 7')
m2 = matrix('1 2 3; 6 8 5; 2 6 7')

In [54]:
print(m1)

[[1 2 3]
 [6 4 5]
 [1 6 7]]


In [55]:
print(diagonal(m1))

[1 4 7]


In [56]:
print(m1.max())

7


In [57]:
# adding matrices
print(m1+m2)

[[ 2  4  6]
 [12 12 10]
 [ 3 12 14]]


In [60]:
print(shape(m1))

(3, 3)


In [61]:
print(shape(m2))

(3, 3)


In [58]:
m3 = m1 * m2;

In [59]:
print(m3)

[[19 36 34]
 [40 74 73]
 [51 92 82]]
