In [4]:
from numpy import *

arr = array([1,2,3,4,5])

arr = arr + 5

print(arr)

[ 6  7  8  9 10]


In [5]:
arr1 = arr
print(arr1)

arr2 = arr + 5
print(arr2)

arr3 = arr1 + arr
print(arr3)

[ 6  7  8  9 10]
[11 12 13 14 15]
[12 14 16 18 20]


In [12]:
#vectorized operations.

print(sin(arr1))

print(cos(arr2))

print(log(arr3))

print(sqrt(arr1))

print(min(arr2))

print(sort(arr3))

print(concatenate([arr1,arr2]))

[-0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.0044257   0.84385396  0.90744678  0.13673722 -0.75968791]
[2.48490665 2.63905733 2.77258872 2.89037176 2.99573227]
[2.44948974 2.64575131 2.82842712 3.         3.16227766]
11
[12 14 16 18 20]
[ 6  7  8  9 10 11 12 13 14 15]


In [13]:
#Copying the array

arr1 = ([1,2,3,4,5,6])

arr2 = arr1

print(arr2)

[1, 2, 3, 4, 5, 6]


In [15]:
# They have same address.
print(id(arr1))

print(id(arr2))

140528451065344
140528451065344


In [17]:
#view function will help to chage the id/address of the array 

arr1 = array([1,2,3,4,5,6,7])

arr2 = arr1.view()

print(id(arr1))
print(id(arr2))

140528450862512
140528450975088


In [20]:
#Two different types of copying: shallow copying and deep coping

#view function for shallow copying.

arr1 = array([1,2,3,4,5,6,7])

arr2 = arr1.view()

#Change of ids for both the arr1 and arr2
print(id(arr1))
print(id(arr2))

#copy function for deep copying

arr1 = array([1,2,3,4,5,6,7])

arr2 = arr1.copy()

# change of id is only for one array.
print(id(arr1))
print(id(arr2))

140528450862512
140528450998160
140528450974896
140528450975952
